export enum AuthEvents {
    SIGNED_IN = "SIGNED_IN",
    SIGNED_OUT = "SIGNED_OUT",
    USER_UPDATED = "USER_UPDATED",
    TOKEN_REFRESHED = "TOKEN_REFRESHED",
    INITIAL_SESSION = "INITIAL_SESSION",
    PASSWORD_RECOVERY = "PASSWORD_RECOVERY",
}